version: '3.7'

services: 
    web:
        container_name: MusicStream
        image: ntrung03/musicstream:latest
        restart: always
        environment: 
            - DEEZER_ARL=${DEEZER_ARL}
            - MUSIXMATCH_USER_TOKEN=${MUSIXMATCH_USER_TOKEN}
            - MUSIXMATCH_OB_USER_TOKEN=${MUSIXMATCH_OB_USER_TOKEN}
            - YOUTUBE_DEVELOPER_KEY=${YOUTUBE_DEVELOPER_KEY}
            - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
            - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
            - RADIO_ENABLED=${RADIO_ENABLED}
        ports:
            - 8080:8080
