#!/bin/sh

if [[ `git status --porcelain www/static/css/style.css` ]]; then
	echo "Changes detected in style.css. Setting cache-busting parameter in index.html"
	sed -i '' -E `printf 's/style.css(\\\?([^\\"]*)v=[^\\&]*([^\\"]*))*/style.css?\\\2v=%s\\\3/g' $(git hash-object www/static/css/style.css | cut -c -6)` www/index.html
	git add www/index.html
fi


if [[ `git status --porcelain www/static/js/script.js` ]]; then
	echo "Changes detected in script.js. Setting cache-busting parameter in index.html"
	sed -i '' -E `printf 's/script.js(\\\?([^\\"]*)v=[^\\&]*([^\\"]*))*/script.js?\\\2v=%s\\\3/g' $(git hash-object www/static/js/script.js | cut -c -6)` www/index.html
	git add www/index.html
fi
