name: Docker
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build & Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Docker build and publish
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ntrung03/musicstream
          tags: latest
