name: Docker
on: [push]
jobs:
  build:
    name: Build & Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Docker build and publish
        uses: whoan/docker-build-with-cache-action@v3.1.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: ntrung03/musicstream
